apiVersion: v2
name: ecommerce
description: Umbrella chart for the ecommerce app
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: backend
    version: 0.1.0
    repository: "file://../backend"
  - name: frontend
    version: 0.1.0
    repository: "file://../frontend"
  - name: database
    version: 0.1.0
    repository: "file://../database"
