apiVersion: v1
kind: Service
metadata:
  name: ecommerce-frontend
  labels:
    app: ecommerce-frontend
spec:
  type: {{ .Values.service.type }}
  selector:
    app: ecommerce-frontend
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 80
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
